app = "republic-yaci-indexer"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[[services]]
  protocol = "tcp"
  internal_port = 2112

  [[services.ports]]
    port = 2112
    handlers = ["http"]

  [services.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 100

  [deploy]
    # keep one machine running; set to 0..
    # to spin up/down on demand
    min_machines_running = 1
    strategy = "rolling"
